[package]
name = "dover"
authors = ["benjamin"]
version = "0.2.4"
edition = "2024"
include = ["src/**/*.rs", "Cargo.toml"]
description = "A CLI tool for summarizing git diffs of Rust code"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bferris413/dover"
homepage = "https://github.com/bferris413/dover"
readme = "README.md"
keywords = ["cli", "git", "diff", "tool"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "dover"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive", "cargo"] }
colored = "3.0.0"
git2 = "0.20.0"
prettyplease = { version = "0.2.29", features = ["verbatim"] }
proc-macro2 = { version = "1.0.94", features = ["span-locations"] }
quote = "1.0.38"
syn = { version = "2.0.96", features = ["extra-traits", "full", "parsing"] }
